[Senator Collins:] It’s a great pleasure, thank you.

[Interviewer:] This ship that was involved in the incident off Western Australia this week…

[Senator Collins:] Yeah, the one the front fell off?

[Interviewer:] Yeah

[Senator Collins:] That’s not very typical, I’d like to make that point.

[Interviewer:] Well, how is it untypical?

[Senator Collins:] Well, there are a lot of these ships going around the world all the time, and very seldom does anything like this happen … I just don’t want people thinking that tankers aren’t safe.

[Interviewer:] Was this tanker safe?

[Senator Collins:] Well I was thinking more about the other ones…

[Interviewer:] The ones that are safe,,,

[Senator Collins:] Yeah,,, the ones the front doesn’t fall off.

[Interviewer:] Well, if this wasn’t safe, why did it have 80,000 tonnes of oil on it?

[Senator Collins:] Well, I’m not saying it wasn’t safe, it’s just perhaps not quite as safe as some of the other ones.

[Interviewer:] Why?

[Senator Collins:] Well, some of them are built so the front doesn’t fall off at all.

[Interviewer:] Wasn’t this built so the front wouldn’t fall off?

[Senator Collins:] Well, obviously not.



